mysql:
  dsn: root:Aa602107@tcp(localhost:3306)/chat_server?charset=utf8mb4&parseTime=True&loc=Local
  name: root
  password: Aa602107
  url: 127.0.0.1
  port: 3306

redis:
  addr: "localhost:6379"
  password: ""
  DB: 0
  poolSize: 30
  minIdleConn: 30